### ISSUE TITLE
Thank you for your work!

### ISSUE THREAD

**Issue by Ninooch** [colinvella/phaser-tilemap-plus#2]
Hi! 
Thank you a lot for your efforts !! This is exactly what I needed ! I'm sorry, I posted an issue before , and I found a solution ( it was due to the compression system I used in Tiled... and it wasn't due to anything in your work.) 
I'm really sorry for the troubles. 

Thank you again !

**Comment by colinvella** [comment]
Hi,

Apologies for the late reply. I'm glad you sorted out the problem, whatever it was! 😊

Cheers!
