### ISSUE TITLE
cannot read property 'plus' of undefined

### ISSUE THREAD

**Issue by Raagh** [colinvella/phaser-tilemap-plus#7]
basically the plugin doesn't seems to be loaded, but its recognised when using plugins.add. I tried reading tilemap from this. and this.game. Cant seem to find the loaded plugin. I have stolen code from your demo to see if I could make it work.

do you mind taking a look at my code? sorry for the trouble and thanks for this amazing plugin :)

https://github.com/Raagh/a-game-needs-no-name

npm install && npm run web

**Comment by colinvella** [comment]
Hi,

The script section in package.json has scripts "dev", "test" and "deploy" so it's not possible to run "web" because it's not defined.

**Comment by colinvella** [comment]
Hi,

I tried your code - the plugin is loaded and the overridden loader and creation functions are executed. What's your problem exactly?

**Comment by Raagh** [comment]
solve it :) .thanks for your hard work. its an amazing library

**Comment by colinvella** [comment]
Hey,

What was the issue, if I may ask?

Colin
