### ISSUE TITLE
Trigger Tile Animation on Region Based Event

### ISSUE THREAD

**Issue by xtt13** [colinvella/phaser-tilemap-plus#8]
Hello Colin,

do you think if it's somehow possible to trigger a Tile Animation 
on a specific Region Based Event?

I'm trying to animate door tiles in my game, but don't know how to do that without
using Sprite Animations or Tile Sprites. 

I uploaded a GIF to show you what i mean:
https://ibb.co/ijSxmb

Thanks for your help!

**Comment by colinvella** [comment]
Hi,

Some work would need to be done to allow modifications in tilemaps after they are loaded, such as setting tile animations.

There is however another issue - animations loop indefinitely. I don't think using tiled animations for opening doors is the best approach, at least for the time being.

**Comment by xtt13** [comment]
Hmm ok. Thank you for your reply. I'll find a way to solve it.
